### ISSUE TITLE
error in new update

### ISSUE THREAD

**Issue by Spyow7** [Captain-Chaos/WorldPainter#114]
java.lang.RuntimeException: I/O error while exporting world
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:140)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:125)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

Root cause:
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(null:-1)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(null:-1)
	at org.jnbt.XMLTransformer.fromXML(XMLTransformer.java:31)
	at org.pepsoft.worldpainter.exporting.JavaWorldExporter.export(JavaWorldExporter.java:118)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:138)

WorldPainter version: 2.6.0 (20190526184302)

java.version: 1.8.0_201
java.vendor: Oracle Corporation
java.vm.version: 25.201-b09
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\dan_t
user.dir: C:\Program Files\WorldPainter
user.country: GB
user.language: en

Free memory: 283554136 bytes
Total memory size: 713031680 bytes
Max memory size: 5579472896 bytes

World name: RPGStart
Seed: -6695333007242110437
Bounds: -8, -6 => 7, 5
Height: 256
Number of tiles: 192
Layers in use: 
Border: ENDLESS_WATER @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: -1
Hidden layers: [Biome]

**Comment by Thund3rst0rm89** [comment]
Mee too, i find in the white screen a button and there i get this error

![wp export](https://user-images.githubusercontent.com/41584155/58435647-a7934200-80c1-11e9-9ba2-a32456d46c06.jpg)


java.lang.UnsupportedOperationException: Endless border not yet supported for Minecraft 1.13
	at org.pepsoft.worldpainter.exporting.JavaWorldExporter.export(JavaWorldExporter.java:95)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:138)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:125)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

WorldPainter version: 2.6.0 (20190526184302)

java.version: 1.8.0_211
java.vendor: Oracle Corporation
java.vm.version: 25.211-b12
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Thomas
user.dir: F:\WorldPainter
user.country: AT
user.language: de

Free memory: 542486928 bytes
Total memory size: 1293942784 bytes
Max memory size: 13265534976 bytes

World name: world
Seed: -8793039055612325827
Bounds: -40, -40 => 39, 39
Height: 256
Number of tiles: 4968
Layers in use: Void
Border: ENDLESS_VOID @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
I've hidden your comment, @Thund3rst0rm89 , since it had nothing to do with the issue you are commenting on. Please create new issues for separate problems, thanks!

**Comment by Captain-Chaos** [comment]
Thanks for reporting this problem @Spyow7 ! It should be fixed in version 2.6.1 which I just released. If you still encounter problems please feel free to file a new issue!
