### ISSUE TITLE
Issues Installing on Ubuntu Linux

### ISSUE THREAD

**Issue by MggMuggins** [Captain-Chaos/WorldPainter#12]
So I am interested in using your cool software, cause, well, it's cool. Anyway, so I went to install it, and, as many Linux users will find, the installer doesn't seem to have done anything. I then, stupidly, went and downloaded and ran the bash script you provided for installing worldpainter. Unfortunately, I had to terminate that one because I needed to shut down my machine. Now, I looked up your linux troubleshooting, and found the directory to which worldpainter had installed. I ran the command to launch. However, now I get the square startup thing infinity. Let me explain. When I run the script in that directory, it says that it is missing some parameters.

`Could not load Logmanager "org.pepsoft.worldpainter.util.WPLogManager"
java.lang.ClassNotFoundException: org.pepsoft.worldpainter.util.WPLogManager
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.util.logging.LogManager$1.run(LogManager.java:195)
    at java.util.logging.LogManager$1.run(LogManager.java:181)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.util.logging.LogManager.<clinit>(LogManager.java:181)
    at com.install4j.runtime.installer.helper.InstallerUtil.disablePreferencesLogging(InstallerUtil.java:522)
    at com.install4j.runtime.installer.helper.InstallerUtil.<clinit>(InstallerUtil.java:85)
    at com.install4j.runtime.launcher.LauncherIntegration.checkIntegrations(LauncherIntegration.java:42)
    at com.install4j.runtime.launcher.Launcher.init(Launcher.java:106)
    at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:23)
[2016-02-17 15:37:16,388] {INFO  } ( org.pepsoft.worldpainter.Main) Starting WorldPainter 2.1.6 (20160207204020)
[2016-02-17 15:37:16,405] {INFO  } (o.p.worldpainter.Configuration) Loading configuration from /home/******/.worldpainter/config
[2016-02-17 15:37:16,939] {INFO  } ( org.pepsoft.worldpainter.Main) Installation ID: 9b23f8a2-1f8b-4a59-ade9-f0efd4fc9314
[2016-02-17 15:37:17,010] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: DefaultLayerEditorProvider (version 2.1.6)
[2016-02-17 15:37:17,010] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: Default (version 2.1.6)
[2016-02-17 15:37:17,012] {INFO  } (      o.p.w.PrivateContextImpl) Checking for updates`

Here is the full output of the terminal, up until it freezes. Now I have the square icon in the middle of my screen that cannot be moved, closed, or interacted with in any manner. I can close the terminal the process is running in to no avail. My internet activity when I check is so minimal that worldpainter can't be doing anything with it. Please help, I want to use this program. :P
~MggMuggins

**Comment by Captain-Chaos** [comment]
Sorry for never getting back to you. Is this still relevant to you?

**Comment by MggMuggins** [comment]
Well, I have since Re-installed my Ubuntu, and so I'd assume something might work differently. What I might try is the shell install, and I'll let you know if anything comes of it.

**Comment by Captain-Chaos** [comment]
I'll close the issue now, but please feel free to file a new issue if you continue to have trouble installing WorldPainter!

**Comment by MggMuggins** [comment]
Just ran GDebi on that deb file, and it installed really nicely. Works great, and I now know that I really like GDebi...
