### ISSUE TITLE
Export crashes with java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by xunto** [Captain-Chaos/WorldPainter#138]
Export crashes with following error:
```java
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
WorldPainter scripting host version 2.7.3.
Copyright 2011-2019 pepsoft.org, The Netherlands.
This is free software distributed under the terms of the GPL, version 3, a copy
of which you can find in the installation directory.

Executing script "export.js" with arguments "./v38.world"

[ERROR] RuntimeException while exporting region 12,15
java.lang.RuntimeException: Comparison method violates its general contract! (region: java.awt.Point[x=12,y=15])
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:765)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:141)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:694)
	... 4 common frames omitted
[ERROR] RuntimeException occurred while executing export.js
java.lang.RuntimeException: RuntimeException while exporting region12,15
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:308)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The world is so big (10000x10000) with lots of custom layers, so I had to export from plain console using wpscript and thoese vm settings:
```
# Enter one VM parameter per line
# For example, to adjust the maximum memory usage to 512 MB, uncomment the following line:
# -Xmx512m
# To include another file, uncomment the following line:
# -include-options [path to other .vmoption file]
-Xmx28G
-XX:+UseConcMarkSweepGC
-XX:+CMSIncrementalMode
#-XX:+PrintGCDetails
#-XX:+PrintGCTimeStamps
```

I may provide world file but I don't want to do it publicly (as I use it for project where it's important for players not to know what map looks like) and it weights a lot.

**Comment by xunto** [comment]
Tried to export problematic part of the map from worldpainter gui today. It gave some more information and asked to send to worldpainter@pepsoft.org.
```
java.lang.RuntimeException: Comparison method violates its general contract! (region: java.awt.Point[x=12,y=15])
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:765)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Root cause:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)

WorldPainter version: 2.7.3 (20190912231756)

java.version: 1.8.0_152
java.vendor: Oracle Corporation
java.vm.version: 25.152-b16
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Linux
os.arch: amd64
os.version: 5.3.1-arch1-1-ARCH
user.home: /home/pol
user.dir: /home/pol/worldpainter
user.country: GB
user.language: en

Free memory: 2855610240 bytes
Total memory size: 10761203712 bytes
Max memory size: 29995040768 bytes

World name: v38
Seed: -3010105285414934063
Bounds: 0, 0 => 78, 78
Height: 256
Number of tiles: 6241
Layers in use: Chasms, bl_grass_sedges, hc_4_g, rl_grass_moore, dt_2_s, hc_4_w, pb_1, rl_grass, hc_other, rl_4_p, dt_bush_hawthorn, bl_3_l, ml_1_l, ml_2_l, bl_grass_grass, ml_bush_berry, jl_4_b, jl_2_b, kb_3_a, kb_2_a, lc_3_o, ic_2, ku_flower_red, yl_0, rl_2_w, dt_4_a, kb_2_b, ku_1_s, dt_grass_bane, dt_water, bl_bush_bracken, lc_4_a, yl_2_w, fg_flower, kb_1_b, hc_4_p, hc_3_s, hc_bush_berry, yl_4_w, fg_grass_buttercups, ph_bush, ml_3_a, jl_bush_bracken, ml_other, yl_3_w, hc_2_s, hc_grass_yellow, jl_grass, dt_4_d, bl_1_a, yl_bush, ku_1_p, yl_4_a, rl_other, yl_grass_asphodel, ku_3_b, bl_grass, lc_other, ml_4_a, ml_flower_white, ku_4_o, pb_grass_sedges, dt_grass, hc_1_s, rl_3_p, pb_grass_moore, ml_1_c, br_0, ku_2_o, lc_grass_reeds, ml_0, ku_1_a, ku_grass, dt_flower_harlond, br_1, yl_grass_wheat, dt_bush_wormwood, dt_bush_bracken, hc_bush_hawthorn, rl_bush, kb_4_a, yl_bush_birch, yl_grass_buttercups, ml_grass_forest, dt_1_s, hc_3_g, hc_grass_nettles, ml_grass_bedstraw, jl_flower, jl_3_a, dt_3_s, jl_2_a, hc_2_p, fg_other, bl_grass_moore, hc_3_p, ku_flower_blue, rl_grass_sedges, hc_2_g, lc_1_o, ml_bush, lc_2_b, lc_4_d, jl_3_b, yl_grass_trefoil, jl_1_a, dt_flower, ku_1_b, yl_flower, ku_grass_foil, bl_grass_reeds, ku_bush_bracken, br_2, rl_4_b, yl_2_b, ml_3_l, ku_4_p, bh_grass, fg_flower_white, jl_4_a, rl_bush_berry, ml_1_b, ml_2_w, lc_2_d, ml_bush_heath, rl_1_w, ml_grass_wheat, bl_bush_berry, lc_3_d, fg_bush_fern, lc_grass_lichen, kb_1_a, jl_bush, lc_2_o, ph_grass_foil, fg_grass_grass, bh_other, Annotations, lc_4_o, ml_bush_bedstraw, rl_1_a, rl_3_w, ph_grass_bracken, pb_other, bl_1_b, ml_2_b, yl_4_p, hc_1_p, ku_3_o, rl_2_l, bl_2_a, dt_grass_wormwood, fg_bush_berry, rl_3_l, kb_0, hc_flower, lc_bush_bracken, ph_flower_yellow, lc_bush_berry, yl_grass_nightshade, ph_grass_trefoil, jl_grass_reeds, bl_2_l, bl_4_b, ml_grass_grass, jl_other, hc_grass, rl_3_b, rl_2_p, ml_grass_moore, ku_3_p, pb_3, bl_grass_forest, lc_2_w, yl_grass_fescue, ml_3_c, jl_bush_bush, lc_flower, ku_2_b, dt_1_d, ml_grass_rushes, bl_flower_white, hc_0, rl_2_s, lc_2_l, yl_grass, dt_3_o, bl_2_b, lc_3_b, ml_1_w, ku_4_b, dt_bush, yl_3_b, yl_3_p, Lava, yl_grass_dock, lc_3_a, ph_flower_white, pb_grass, ml_grass_sedges, dt_1_o, dt_other, yl_1_p, ku_1_l, lc_1_a, kb_4_a, bl_grass_foil, pb_2, rl_1_p, fg_flower_red, bl_flower, lc_3_w, dt_flower_mithlond, bl_3_a, ph_grass, bl_4_l, rl_grass_grass, ku_bush, rl_flower, rl_1_b, yl_1_b, dt_bush_parsley, rl_flower_blue, pb_bush_hart, hc_1_g, Biome, hc_3_w, kb_3_b, ph_flower, hc_bush, ku_grass_forest, yl_flower_red, ph_grass_simbel, ku_2_l, lc_1_d, bh_bush, yl_other, ku_3_l, lc_1_l, ml_3_w, rl_grass_foil, pb_bush, ku_bush_berry, lc_2_a, dt_3_a, jl_1_b, ml_3_b, lc_1_w, ml_grass, yl_bush_bracken, fg_grass_foil, bl_other, pb_bush_cypress, ic_1, ml_flower_red, rl_bush_bracken, bl_bush_fern, dt_grass_sedge, yl_bush_nettles, bl_flower_blue, ku_0, dt_3_d, yl_1_w, dt_grass_reeds, hc_2_w, bl_bush, yl_2_a, yl_grass_bedstraw, hc_4_s, dt_2_o, jl_0, hc_1_w, bl_3_b, lc_4_w, dt_4_s, bl_0, fg_bush, lc_3_l, fg_grass_moore, rl_1_l, ml_2_c, rl_flower_red, yl_4_b, yl_2_p, lc_0, lc_bush, dt_2_d, ku_2_p, lc_grass_wormwood, ku_2_s, dt_4_o, dt_1_a, bl_grass_worm , ml_1_a, hc_grass_reeds, ml_4_c, kb_4_b, bl_flower_red, rl_0, jl_grass_lichen, hc_bush_cypress, rl_4_w, lc_flower_harlond, lc_flower_heather, ku_other, yl_3_a, ku_flower, ku_4_s, yl_1_a, hc_grass_buttercups, bl_4_a, dt_2_a, lc_1_b, lc_grass, fg_flower_blue, fg_grass, bl_1_l, yl_flower_yellow, ml_flower_yellow, ku_grass_moore, rl_2_b
Border: ENDLESS_VOID @ 43
Sub surface material: Stone Mix
Water height: 43

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: -2
Hidden layers: [Biome]
```
