### ISSUE TITLE
Error after changing GUI scale in preferences

### ISSUE THREAD

**Issue by louieDep** [Captain-Chaos/WorldPainter#160]
Any thoughts?

Is there a way I can delete preferences with losing my customizations?

Tx.

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:351)
	at com.apple.laf.AquaImageFactory.getAppIconImageCompositedOn(AquaImageFactory.java:131)
	at com.apple.laf.AquaImageFactory.lambda$getAppIconCompositedOn$0(AquaImageFactory.java:111)
	at sun.awt.image.MultiResolutionCachedImage.lambda$map$1(MultiResolutionCachedImage.java:83)

WorldPainter version: 2.7.7 (20200425182227)

java.version: 1.8.0_231
java.vendor: Oracle Corporation
java.vm.version: 25.231-b11
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Mac OS X
os.arch: x86_64
os.version: 10.14.6
user.home: /Users/Andy
user.dir: /Applications/WorldPainter.app/Contents/java/app
user.country: US
user.language: en

Free memory: 307564280 bytes
Total memory size: 409993216 bytes
Max memory size: 28633464832 bytes

**Comment by Captain-Chaos** [comment]
Looks like this may not work on a Mac; that's hard to test for me unfortunately because I don't own one.

You can reset your configuration by deleting the config file at ~/Library/Application Support/WorldPainter/config. It does mean losing your preferences. I'm not sure what other customizations you mean, but it will not affect your custom brushes, for instance.

**Comment by louieDep** [comment]
CC, 

 

Thanks for the heads up.

 

-AD
