### ISSUE TITLE
[Bug] IndexOutOfBounds on merge

### ISSUE THREAD

**Issue by 1Jajen1** [Captain-Chaos/WorldPainter#176]
Hi, I am currently getting this error while trying to merge:

```
java.lang.IndexOutOfBoundsException: Index: 17, Size: 17
	at java.util.ArrayList.rangeCheck(null:-1)
	at java.util.ArrayList.get(null:-1)
	at java.util.Collections$UnmodifiableList.get(null:-1)
	at org.pepsoft.minecraft.MC114AnvilChunk$Section.getMaterial(MC114AnvilChunk.java:863)
	at org.pepsoft.minecraft.MC114AnvilChunk$Section.<init>(MC114AnvilChunk.java:718)
	at org.pepsoft.minecraft.MC114AnvilChunk.<init>(MC114AnvilChunk.java:67)
	at org.pepsoft.worldpainter.DefaultPlatformProvider.createChunk(DefaultPlatformProvider.java:49)
	at org.pepsoft.worldpainter.DefaultPlatformProvider.createChunk(DefaultPlatformProvider.java:38)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.thirdPass(JavaWorldMerger.java:956)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.mergeRegion(JavaWorldMerger.java:757)
WorldPainter version: 2.7.16 (20200614113037)
Free memory: 1050393648 bytes
Total memory size: 2065170432 bytes
Max memory size: 5669126144 bytes
World name: Generated World
Seed: -4993149450430957260
Bounds: -2, -2 => 2, 2
Height: 256
Number of tiles: 25
Layers in use:
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62
Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]
```

> Note I am using 1.16 so I kind of expected things to go wrong, but after looking at the code this should not be happening regardless of version. I also omitted jvm info and some other minor details that should not be relevant to this at all.

I am not sure how easy this is to recreate, but all I did was create a new map, export it, open in minecraft 1.16, close it and merge the map again.

Given that this only happens with index >= 16 (mostly 17, but iirc I had one 16 in there was well) this is most likely an issue with parsing the palette index from the variable value array. Up to 16 the palette would use 4 bits and thus take the special case, it is only after that that it uses the bitset for parsing.

I'll try around today and see if I can fix this myself, but if anyone has an idea before I get a pr ready please go ahead :)

**Comment by 1Jajen1** [comment]
Ah never mind, block states format changes in 1.16. Forgot that (despite having implemented that in a different tool a week or so ago :see_no_evil:)

@Captain-Chaos ignoring the above, what would need to change for 1.16 support? I am quite interested in adding that :)
