### ISSUE TITLE
Custom World 1.15 Generator Error

### ISSUE THREAD

**Issue by TeslaGamingYT** [Captain-Chaos/WorldPainter#210]
Hello, I seem to be running into an error with World Painter today. I loaded a fresh brand new auto made world on World Painter and I tried to export it and set the settings to custom world type, entered in "cool" and then it gave me this lovely error

java.lang.IllegalArgumentException: Use setGeneratorName(String) for generator BUFFET
	at org.pepsoft.minecraft.Level.setGenerator(Level.java:344)
	at org.pepsoft.worldpainter.exporting.JavaWorldExporter.export(JavaWorldExporter.java:145)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:138)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:125)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

WorldPainter version: 2.8.1 (20210528190007)

java.version: 1.8.0_301
java.vendor: Oracle Corporation
java.vm.version: 25.301-b09
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\PureL
user.dir: C:\Program Files\WorldPainter
user.country: US
user.language: en

Free memory: 241276368 bytes
Total memory size: 307232768 bytes
Max memory size: 13293322240 bytes

World name: Generated World
Seed: -1902768145625651069
Bounds: -2, -2 => 2, 2
Height: 256
Number of tiles: 25
Layers in use: 
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

I then made an attempt at trying to change the custom name to "BUFFET" and it ended up giving the same error. any help is greatly appreciated :D

**Comment by TeslaGamingYT** [comment]
Nevermind, I'm an idiot
I needed to add more biomes
