### ISSUE TITLE
Error while exporting world

### ISSUE THREAD

**Issue by DayzDuck** [Captain-Chaos/WorldPainter#227]
I'm not a pro, however, no matter what version, when I try to export the map I get an error. Can I solve this somehow?
Thank you in advance for the help
the only thing i  can see is:
`java.lang.RuntimeException: Don't know how to support cement yet`
but how can is support it?
```
java.lang.RuntimeException: Don't know how to support cement yet (region: java.awt.Point[x=7,y=-27])
    at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:769)
    at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:279)
    at org.pepsoft.util.mdc.MDCThreadPoolExecutor.lambda$wrap$0(MDCThreadPoolExecutor.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(null:-1)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(null:-1)
    at java.lang.Thread.run(null:-1)

Root cause:
java.lang.UnsupportedOperationException: Don't know how to support cement yet
    at org.pepsoft.worldpainter.platforms.Java1_15PostProcessor.postProcess(Java1_15PostProcessor.java:191)
    at org.pepsoft.worldpainter.exporting.PostProcessor.postProcess(PostProcessor.java:36)
    at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:750)
    at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:279)
    at org.pepsoft.util.mdc.MDCThreadPoolExecutor.lambda$wrap$0(MDCThreadPoolExecutor.java:55)

WorldPainter version: 2.8.10 (20211211153027)

java.version: 1.8.0_321
java.vendor: Oracle Corporation
java.vm.version: 25.321-b07
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Lennart
user.dir: E:\Aiena\WorldPainter Programm
user.country: DE
user.language: de

Free memory: 8373166480 bytes
Total memory size: 17657495552 bytes
Max memory size: 28549578752 bytes

World name: Aiena 4
Seed: 7518529081242484698
Bounds: -120, -146 => 119, 145
Height: 256
Number of tiles: 70080
Layers in use: 12_SavanneSumpf, Sivitaner, 42_Wucher, Miri_heftig, BlaueBlumenundFern, Zucker, Jungle_Hochland, FeldBeete, HoraSteppe, Cactus, Tunnel random, ScanuriWald, Fichtenwald_Engolund, 52_SavannenBäume01, Nordwald, Toter busch, Kornhöfe Wald, Fern, Jungle, Coralenriff, spain_palm, Fichtenwald, Sumpf, SumpforksTrees, JungleBlumen, Fuchswald, Deciduous, MongolenBergJungle, 12_Viking_Beach, UltraJungle, Bamboo, TomatanaEbene, AkazienSavanne, TausendHecken, Jungletunnel, 58_Wald, Flettenlande, Rok`holWald, SchwarzeisenWald, Biome, Hedges, Sivitaner Unterholz, BerryBush, 51_Indienwald, Marlis_Jungle, FeldKartoffel, TefraWald, Melonen, Kleine Fichten und Steine, PilzeRot, WitherRose, Fels und Busch2, flauschiger_wald, Valencio Hedges, Abgeholzt, spain_forrest, Orks, Lava, NordAlpinDunkel, Steppe01, MaximalGrass, PilzeBraun, RedWoodSmall, TalkisterWald, Savanne Mongolai, FeldKorn, TunnelDover, 36_Jungle, TunnelBerge, 10Wald, Kelp, SivitanerFluss, 12_Viking_Wald, Miri_heftigGrass, FeldKarotten, 10HoherWald, Packed Ice, Kleine Tannen, orks2, 8_Wald, Mischwald_Engolund, Flettenwald, Frost, Seegrass, Kürbis, Savanne kurz dunkel, EisUntergrund, SelectionBlock, Gras, spain_land, 12_Viking_Flat, heftigerbusch, Pink_Coral, GrosseBlume, 51_Granitbuschland, TalkisterTal, TausendHeckenWald, LavenderFeld, 8_Küste, Bach, Kernprovinzen Wald, Annotations, Birkenjungle, HoraTal, Karibik_Dicht, Regenwaldsmpf, NurBirken, Redwood, River, TunnelSivitaner, BambooJungle, Karibik_Küste, Fels und Busch1, Gelbe Blumen, wüstenbüsche, Seerosen
Border: ENDLESS_WATER @ 48
Sub surface material: Stone Mix
Water height: 48

Operation: Pencil
Radius: 270
Brush: org.pepsoft.worldpainter.brushes.BitmapBrush@1b47ffe1/Spike Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.79/0.51
Zoom: -2
Hidden layers: [Biome]
```

**Comment by Captain-Chaos** [comment]
Someone (not you?) has set the Post Processing setting (on the Export screen) for floating cement blocks to "support with stone". That isn't supported yet. I'll add support in the next release, but in the mean time you can set that to "leave floating" or "drop" and it should work.
