### ISSUE TITLE
[bug] Some special settings will cause IllegalArgumentException when importing from height map.

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#238]
### Cannot import again after this time.
![2Z~3XJ`P9`1CI IS P8 N43](https://user-images.githubusercontent.com/46108547/166297808-8258ba71-1e09-4784-96b8-26ca14c5c996.png)
![YMJ`JY2@4{F_L88GYL5M@5U](https://user-images.githubusercontent.com/46108547/166297816-d50ec200-26c3-4cd4-8898-cfa7193953ee.png)

details: 
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:139)
	at javax.swing.SpinnerNumberModel.<init>(SpinnerNumberModel.java:161)
	at org.pepsoft.worldpainter.themes.impl.simple.SimpleThemeEditor.setTheme(SimpleThemeEditor.java:90)
	at org.pepsoft.worldpainter.ImportHeightMapDialog.loadDefaults(ImportHeightMapDialog.java:419)
	at org.pepsoft.worldpainter.ImportHeightMapDialog.<init>(ImportHeightMapDialog.java:118)
	at org.pepsoft.worldpainter.ImportHeightMapDialog.<init>(ImportHeightMapDialog.java:67)
	at org.pepsoft.worldpainter.App.importHeightMap(App.java:2413)
	at org.pepsoft.worldpainter.App.lambda$createFileMenu$36(App.java:3897)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)

WorldPainter version: 2.9.1 (20220502115841)

java.version: 17.0.3
java.vendor: Oracle Corporation
java.vm.version: 17.0.3+8-LTS-111
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Harvey
user.dir: D:\Softwares\WorldPainter
user.country: CN
user.language: zh

Free memory: 174299120 bytes
Total memory size: 469762048 bytes
Max memory size: 32161923072 bytes

World name: 武汉高程 (1)
Seed: 8393571809061657212
Bounds: 0, 0 => 19, 19
Height: 320
Number of tiles: 400
Layers in use: Frost
Border: null @ -1
Sub surface material: Stone Mix
Water height: -1

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=7, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
Thanks for reporting this! I'll look into the bug.

In the mean time you should be able to get height map imports to work again by deleting the config file (`%APPDATA%\WorldPainter\config`).

**Comment by Captain-Chaos** [comment]
But I think you probably know that or you wouldn't have been able to get those screenshots. 😀

**Comment by Harveykang** [comment]
yep :P, thank you anyway

**Comment by Captain-Chaos** [comment]
This will be fixed in version 2.9.2.
