### ISSUE TITLE
Issue Merging Worlds (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by Defjer** [Captain-Chaos/WorldPainter#255]
Only recently found out about world painter and began using it on a map I've been building on for the past 2 years. 

I've tested out the merge function on some other 1.18 worlds of mine and they work just fine, just this one specifically I end up with this message constantly 
![image](https://user-images.githubusercontent.com/106018487/169695481-4eb517e9-fcf4-48f2-b22a-816a4ae555a5.png)

```
java.lang.ArrayIndexOutOfBoundsException: -4
	at org.pepsoft.minecraft.MC115AnvilChunk.getMaterial(MC115AnvilChunk.java:494)
	at org.pepsoft.worldpainter.exporting.WorldRegion.getMaterialAt(WorldRegion.java:82)
	at org.pepsoft.worldpainter.platforms.Java1_15PostProcessor.postProcess(Java1_15PostProcessor.java:91)
	at org.pepsoft.worldpainter.exporting.PostProcessor.postProcess(PostProcessor.java:36)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.mergeRegion(JavaWorldMerger.java:821)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.lambda$mergeDimension$6(JavaWorldMerger.java:535)
	at org.pepsoft.util.mdc.MDCThreadPoolExecutor.lambda$wrap$0(MDCThreadPoolExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(null:-1)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(null:-1)
	at java.lang.Thread.run(null:-1)

WorldPainter version: 2.10.5 (20220518134452)

java.version: 1.8.0_321
java.vendor: Oracle Corporation
java.vm.version: 25.321-b07
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\rpbub
user.dir: C:\Program Files\WorldPainter
user.country: US
user.language: en

Free memory: 2788669672 bytes
Total memory size: 4150788096 bytes
Max memory size: 13181648896 bytes

World name: RoP
Platform: [BETA] Minecraft 1.18 or later (org.pepsoft.anvil.1.18)
Seed: -8447611311500529190
Bounds: -233617, -233117 => 233779, 234137
Height: 320
Number of tiles: 3090
Layers in use: Annotations, Biome, Lava, Frost, Void, Not Present
Border: null @ 62
Sub surface material: Stone
Water height: 62
World imported from C:\Users\rpbub\AppData\Roaming\.minecraft\saves\Medieval map for an rp (DO NOT DELETE PLEASE)\level.dat

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=7, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: -2
Hidden layers: [Biome]
```

Any help would be greatly appreciated, thanks.

**Comment by Captain-Chaos** [comment]
It means that map has old, non 1.18 chunks in it which WorldPainter can't merge. You probably got a warning that this would happen when you Imported that map.

You should be able to fix it by using the Optimize function of Minecraft to fully convert that map to 1.18. I'll see if I can improve the error message, but since this isn't a bug in WorldPainter I'll close the issue. Let me know how you get on and feel free to file a new issue if you still encounter a problem.
