### ISSUE TITLE
Error stops world merge (1.17 map)

### ISSUE THREAD

**Issue by Antlucl** [Captain-Chaos/WorldPainter#269]
Hello! When attempting to start a merge, it simply directly refuses once I press the merge button. I am attempting to merge a 1.17 worldpainter type map with a 1.17(.1) Minecraft map, with the "Completely replace chunks with new chunks" option. I have then used the merge select tile option to avoid replacing built structures that are already there on the map. I am using the newest version of WorldPainter.

java.lang.NullPointerException: Cannot invoke "org.pepsoft.worldpainter.Tile.getLayers()" because the return value of "org.pepsoft.worldpainter.Dimension.getTile(java.awt.Point)" is null
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.setupDimensionForExport(AbstractWorldExporter.java:387)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.mergeDimension(JavaWorldMerger.java:432)
	at org.pepsoft.worldpainter.merging.JavaWorldMerger.merge(JavaWorldMerger.java:321)
	at org.pepsoft.worldpainter.MergeProgressDialog$1.execute(MergeProgressDialog.java:89)
	at org.pepsoft.worldpainter.MergeProgressDialog$1.execute(MergeProgressDialog.java:79)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

My best guess based on the error is that some kind of layer is causing the error, but I have been able to figure out which/how and how to resolve it. I'm not good at programming, so I could be completely wrong also.

I would be very thankful for any help, and if there's any additional information/data that's needed, please let me know and I will provide it. Have a nice day.

**Comment by Captain-Chaos** [comment]
Does it only happen with one particular map and/or world? If so could you send me those? If not, can you give me some steps to reproduce this?

**Comment by Captain-Chaos** [comment]
Since I haven't heard back from you I'm going to close this. If it still happens feel free to open a new issue! I'm going to need more details from you in order to get to the bottom of it though.
