### ISSUE TITLE
Random crashed in wpscript.exe

### ISSUE THREAD

**Issue by MattiBorchers** [Captain-Chaos/WorldPainter#281]
For some time now I have been getting random crashes in the Scripting Engine.

If I run the same script again, it usually works. The error occurs about 1 time out of 10.

Also the line in my wpscript.js varies, in this time, 1022 only has the following code: ```.fromColour(203,17,181).toLevel(BIOME_TAIGA)```

```
java.lang.AssertionError: Failed generating bytecode for wpscript.js:1022
        at org.openjdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:437)
        at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614)
        at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641)
        at org.openjdk.nashorn.internal.runtime.RecompilableScriptFunctionData.compileTypeSpecialization(RecompilableScriptFunctionData.java:730)
        at org.openjdk.nashorn.internal.runtime.RecompilableScriptFunctionData.getBest(RecompilableScriptFunctionData.java:910)
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.getBest(ScriptFunctionData.java:384)
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.getBestInvoker(ScriptFunctionData.java:244)
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.findCallMethod(ScriptFunction.java:917)
        at org.openjdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1881)
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:109)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.lambda$getGuardedInvocation$0(LinkerServicesImpl.java:137)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getWithLookupInternal(LinkerServicesImpl.java:168)
        at jdk.dynalink/jdk.dynalink.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:135)
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.createApplyOrCallCall(ScriptFunction.java:1113)
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.findCallMethod(ScriptFunction.java:908)
        at org.openjdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1881)
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
        at org.openjdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:96)
        at jdk.dynalink/jdk.dynalink.linker.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:161)
```

Full error: https://pastebin.com/XvyfQ1Ti

**Comment by MattiBorchers** [comment]
Ok I might find the reason / the answer. Seems like the thread stack size is to small for my very long script.
I added ```-Xss64M``` as a startup parameter to the wpscript.moptions and now I don't get the error anymore.

Still watching the problem it was just luck or really the answer :)

**Comment by Captain-Chaos** [comment]
Can you upload the script?

**Comment by MattiBorchers** [comment]
Thats exactly what's happening. Good idea with the intermediate variable. Was also thinking about "applying the heightmap" multiple times and use only a part of the colors.
