### ISSUE TITLE
Biomes viewer may pick Forge Minecraft installation instead of vanilla

### ISSUE THREAD

**Issue by Barteks2x** [Captain-Chaos/WorldPainter#292]
The exception:
```
[2023-01-02 10:57:41,367] {INFO  } (    o.p.w.b.BiomeSchemeManager) Creating biome scheme 1.12.2 or 1.7.2 - 1.10.2 from /home/bartosz/.minecraft/versions/1.12.2-forge-14.23.5.2860/1.12.2-forge-14.23.5.2860.jar
[2023-01-02 10:57:41,457] {ERROR } (    o.p.w.b.BiomeSchemeManager) RuntimeException while instantiating biome scheme of type org.pepsoft.worldpainter.biomeschemes.Minecraft1_12LargeBiomeScheme from /home/bartosz/.minecraft/versions/1.12.2-forge-14.23.5.2860/1.12.2-forge-14.23.5.2860.jar

java.lang.RuntimeException: Exception thrown while instantiating biome scheme
	at org.pepsoft.worldpainter.biomeschemes.BiomeSchemeManager$BiomeSchemeDescriptor.instantiate(BiomeSchemeManager.java:475)
	at org.pepsoft.worldpainter.biomeschemes.BiomeSchemeManager.getBiomeScheme(BiomeSchemeManager.java:86)
	at org.pepsoft.worldpainter.biomeschemes.BiomeSchemeManager.getNewBiomeScheme(BiomeSchemeManager.java:32)
	at org.pepsoft.worldpainter.tools.BiomesViewerFrame.<init>(BiomesViewerFrame.java:111)
	at org.pepsoft.worldpainter.App.lambda$createToolsMenu$72(App.java:4461)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.pepsoft.worldpainter.biomeschemes.BiomeSchemeManager$BiomeSchemeDescriptor.instantiate(BiomeSchemeManager.java:466)
	... 42 common frames omitted
Caused by: java.lang.RuntimeException: Exception thrown while trying to initialise Minecraft
	at org.pepsoft.worldpainter.biomeschemes.Minecraft1_12JarBiomeScheme.<init>(Minecraft1_12JarBiomeScheme.java:48)
	at org.pepsoft.worldpainter.biomeschemes.Minecraft1_12LargeBiomeScheme.<init>(Minecraft1_12LargeBiomeScheme.java:20)
	... 47 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.pepsoft.worldpainter.biomeschemes.Minecraft1_12JarBiomeScheme.init(Minecraft1_12JarBiomeScheme.java:102)
	at org.pepsoft.worldpainter.biomeschemes.Minecraft1_12LargeBiomeScheme.init(Minecraft1_12LargeBiomeScheme.java:39)
	at org.pepsoft.worldpainter.biomeschemes.Minecraft1_12JarBiomeScheme.<init>(Minecraft1_12JarBiomeScheme.java:42)
	... 48 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at nf.<init>(SourceFile:25)
	at nf.<init>(SourceFile:32)
	at qe.a(SourceFile:574)
	at qe.b(SourceFile:20)
	at ni.c(SourceFile:466)
	... 55 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 60 common frames omitted
```

As seen in this part of the log, it's attempting to use the forge jar and version json.

**Comment by Captain-Chaos** [comment]
This will be fixed in the next release (2.15.19).
