### ISSUE TITLE
[Bug] Big masks can't be imported

### ISSUE THREAD

**Issue by Taiyou06** [Captain-Chaos/WorldPainter#321]
```
java.lang.IllegalArgumentException: Invalid scanline stride
	at java.awt.image.ComponentSampleModel.getBufferSize(ComponentSampleModel.java:265)
	at java.awt.image.ComponentSampleModel.verify(ComponentSampleModel.java:243)
	at java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:158)
	at java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.awt.image.PixelInterleavedSampleModel.createCompatibleSampleModel(PixelInterleavedSampleModel.java:144)
	at javax.imageio.ImageTypeSpecifier.getSampleModel(ImageTypeSpecifier.java:1039)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1072)
	at javax.imageio.ImageReader.getDestination(ImageReader.java:2877)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1488)
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1847)

```

The mask im trying to import is this: https://drive.google.com/file/d/1hLZUpZQEAT4m87WEG0-8OyVbDSPQa9rj/view?usp=sharing

**Comment by Captain-Chaos** [comment]
Unfortunately there's nothing I can do about that. It's a limitation in Java. You'll have to try and reduce the size, for example by dividing it into multiple smaller pieces that you import separately, and/or by reducing the bit depth.
