### ISSUE TITLE
Error when attempting to add variation to biome

### ISSUE THREAD

**Issue by Dannypan** [Captain-Chaos/WorldPainter#351]
When attempting to add a variation to a biome, ie changing ocean to frozen ocean, an error popup shows:

![image](https://github.com/Captain-Chaos/WorldPainter/assets/39864044/07ec2de7-71fe-477f-8f3e-e69798cd1c24)

Copied error:

java.lang.ClassCastException: class javax.swing.JLabel cannot be cast to class javax.swing.JCheckBox (javax.swing.JLabel and javax.swing.JCheckBox are in module java.desktop of loader 'bootstrap')
	at org.pepsoft.worldpainter.layers.BiomesPanel.getSelectedOptions(BiomesPanel.java:314)
	at org.pepsoft.worldpainter.layers.BiomesPanel.updateOptions(BiomesPanel.java:282)
	at org.pepsoft.worldpainter.layers.BiomesPanel.lambda$resetOptions$3(BiomesPanel.java:268)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:411)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6626)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389)

WorldPainter version: 2.21.0 (20230820171647)

java.version: 17.0.7
java.vendor: Oracle Corporation
java.vm.version: 17.0.7+8-LTS-224
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 11
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Reception
user.dir: C:\Program Files\WorldPainter
user.country: GB
user.language: en

Free memory: 1250362632 bytes
Total memory size: 2181038080 bytes
Max memory size: 14839447552 bytes

World name: Skyrim Inspired Test
Platform: Minecraft 1.19 or later (org.pepsoft.anvil.1.19)
Seed: 6104057691700770006
Bounds: -4, -4 => 3, 3
Height: 512
Number of tiles: 64
Layers in use: 
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: Height
Radius: 40
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/org.pepsoft.worldpainter.brushes.BitmapBrush@66965b98
Level: 0.51/1.0
Zoom: 1
Hidden layers: [Biome]

**Comment by Dannypan** [comment]
Further testing: closing the error popup is fine but the biome variation won't be considered when painting, you only get the base biome, ie I can't paint Flower Forest, just Forest.

**Comment by Dannypan** [comment]
As requested - [logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/12395370/logfile0.txt)

**Comment by Captain-Chaos** [comment]
This will be fixed in the next release.
