### ISSUE TITLE
wpscript exception when creating a new filter

### ISSUE THREAD

**Issue by DerMattinger** [Captain-Chaos/WorldPainter#362]
With the latest update(s) I got an exception when I use my old script.

Here is the error log:

`java.lang.NullPointerException: dimension
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at org.pepsoft.worldpainter.panels.TerrainOrLayerFilter.<init>(TerrainOrLayerFilter.java:16)
        at org.pepsoft.worldpainter.panels.ExceptOnTerrainOrLayerFilter.<init>(ExceptOnTerrainOrLayerFilter.java:15)
        at org.pepsoft.worldpainter.panels.ExceptOnTerrainOrLayerFilter.create(ExceptOnTerrainOrLayerFilter.java:97)
        at org.pepsoft.worldpainter.panels.DefaultFilter.<init>(DefaultFilter.java:53)
        at org.pepsoft.worldpainter.tools.scripts.CreateFilterOp.go(CreateFilterOp.java:292)
        at org.pepsoft.worldpainter.tools.scripts.CreateFilterOp.go(CreateFilterOp.java:36)
        at org.openjdk.nashorn.internal.scripts.Script$Recompilation$3$268435452A$wpscript.:program$:split-7(wpscript.js:1299)`

Line 1299 of my script contains the following simple part:

var noWaterFilter = wp.createFilter()
.exceptOnTerrain(37)
.go();

**Comment by Captain-Chaos** [comment]
This should be fixed in version 2.22.0.
