### ISSUE TITLE
Can't export because custom annotations aren't supported for cave floors

### ISSUE THREAD

**Issue by Dannypan** [Captain-Chaos/WorldPainter#369]
Not the end of the world as I can just remove the layer for now, but could you please add support? 

Thank you!

```
java.lang.UnsupportedOperationException: Layer Cave Wall Mask of type CustomAnnotationLayer not yet supported for cave floor dimensions
	at org.pepsoft.worldpainter.layers.tunnel.TunnelLayerExporter.lambda$carve$5(TunnelLayerExporter.java:257)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

Diagnostic context:
	baseDir: C:\Users\Reception\AppData\Roaming\.minecraft\saves
	dimension.anchor: 0 DETAIL
	dimension.maxHeight: 512
	dimension.minHeight: -64
	platform.id: org.pepsoft.anvil.1.19
	region.coords: java.awt.Point[x=2,y=-11]
	world.maxHeight: 512
	world.minHeight: -64
	world.name: New Aeosta

WorldPainter version: 2.22.0 (20231203181656)

java.version: 17.0.7
java.vendor: Oracle Corporation
java.vm.version: 17.0.7+8-LTS-224
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 11
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Reception
user.dir: C:\Program Files\WorldPainter
user.country: GB
user.language: en

Free memory: 4428750912 bytes
Total memory size: 6912212992 bytes
Max memory size: 14839447552 bytes


```

**Comment by Captain-Chaos** [comment]
This will be fixed in the next release.
