### ISSUE TITLE
[BUG] Cannot load a compressed int16 TIF from scripts

### ISSUE THREAD

**Issue by atmosphericbeats** [Captain-Chaos/WorldPainter#390]
When I try to load a compressed TIF (LZW predictor=2) from a script using 

`var heightMap = wp.getHeightMap().fromFile('test.tif').go();`

I got this error. However, **if I load the same TIF from the GUI, the heightmap is correctly imported into the map**:

`
[ERROR] RuntimeException occurred while executing worldpainter.js
java.lang.RuntimeException: org.pepsoft.worldpainter.tools.scripts.ScriptException: I/O error while loading image E:/mcmaps_auto/vietnam30m/dem_osm_corrected.tif

Caused by: org.pepsoft.worldpainter.tools.scripts.ScriptException: I/O error while loading image E:/mcmaps_auto/vietnam30m/dem_osm_corrected.tif
        at org.pepsoft.worldpainter.tools.scripts.GetHeightMapOp.go(GetHeightMapOp.java:84)
        at org.openjdk.nashorn.internal.scripts.Script$worldpainter.:program(worldpainter.js:27)
        at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:646)
        at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520)
        ... 11 common frames omitted

Caused by: javax.imageio.IIOException: **16-bit samples are not supported for Horizontal differencing Predictor**
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFLZWDecompressor.decodeRaw(TIFFLZWDecompressor.java:90)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFDecompressor.decodeRaw(TIFFDecompressor.java:1911)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2553)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1142)
        at java.desktop/com.sun.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1361)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1466)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
        at org.pepsoft.worldpainter.tools.scripts.GetHeightMapOp.go(GetHeightMapOp.java:73)
        ... 15 common frames omitted
`

**Comment by Captain-Chaos** [comment]
It's extremely strange that the same script work when you run it from the GUI, not not from `wpscript`. It's the same code that gets invoked. Is it possible that when you run `wpscript` from the command line a different Java version is the default than when you run the GUI?
