### ISSUE TITLE
NPE when loading worlds with combined layers with custom terrains

### ISSUE THREAD

**Issue by Captain-Chaos** [Captain-Chaos/WorldPainter#42]
```
java.lang.NullPointerException: null
at org.pepsoft.worldpainter.App.clearCustomTerrains(App.java:4797)
at org.pepsoft.worldpainter.App.loadCustomTerrains(App.java:4811)
at org.pepsoft.worldpainter.App.setWorld(App.java:307)
at org.pepsoft.worldpainter.App.open(App.java:983)
at org.pepsoft.worldpainter.App.open(App.java:763)
```

**Comment by Captain-Chaos** [comment]
Analysis: this happens because the deserialisation of the combined layer already registers the custom terrain type, if it contains one, without adding a button for it. The fix is to refactor this mechanism.
