### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Clexus** [Captain-Chaos/WorldPainter#431]
```
java.lang.IllegalAccessError: superclass access check failed: class com.jidesoft.plaf.windows.XPStyle$SkinPainter (in unnamed module @0x58a9760d) cannot access class sun.swing.CachedPainter (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x58a9760d
	at java.lang.ClassLoader.defineClass1(ClassLoader.java:-2)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1023)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at com.jidesoft.plaf.windows.XPStyle.<clinit>(null:-1)

WorldPainter version: 2.23.3-SNAPSHOT ()

java.version: 22.0.1
java.vendor: Oracle Corporation
java.vm.version: 22.0.1+8-16
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\1111
user.dir: C:\Users\1111\Desktop\Development\Development\WorldPainter-Chinese
user.country: CN
user.language: zh

Free memory: 38614808 bytes
Total memory size: 83886080 bytes
Max memory size: 8380219392 bytes
```

**Comment by Captain-Chaos** [comment]
Sorry, but this is a bug in Java and/or Jide, possibly in combination with the Chinese locale, which I cannot do anything about. Can you try changing the visual theme? The exception seems to occur in Jide's Windows look-and-feel (which it uses when you select the System visual theme on Windows), so I expect other visual themes will work.
