### ISSUE TITLE
Progress reporting in task bar crashes on Windows versions older than 7

### ISSUE THREAD

**Issue by Captain-Chaos** [Captain-Chaos/WorldPainter#44]
```
java.lang.RuntimeException: Interface does not inherit from class
	at org.bridj.cpp.com.COMRuntime.error(COMRuntime.java:187)
	at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:271)
	at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:258)
	at org.pepsoft.util.ProgressHelper.<init>(ProgressHelper.java:19)
	at org.pepsoft.util.ProgressHelper.setProgress(ProgressHelper.java:30)
	at org.pepsoft.util.DesktopUtils.lambda$setProgress$0(DesktopUtils.java:161)
	at org.pepsoft.util.DesktopUtils$$Lambda$207/11031984.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
```

**Comment by Captain-Chaos** [comment]
Analysis: apparently this only works from Windows 7 and up and throws an exception on older versions. Solution: catch the exception and disable the mechanism
