### ISSUE TITLE
NullPointerException somewhere

### ISSUE THREAD

**Issue by vkb24312** [Captain-Chaos/WorldPainter#69]
I got a nullPointerException. Here's the stacktrace and some other information I was told to give :/
I can't remember when I got it, however it was right after I made the new world

java.lang.NullPointerException: null
	at org.pepsoft.util.swing.TiledImageViewer.removeTileProvider(TiledImageViewer.java:225)
	at org.pepsoft.util.swing.TiledImageViewer.setTileProvider(TiledImageViewer.java:133)
	at org.pepsoft.util.swing.TiledImageViewer.setTileProvider(TiledImageViewer.java:120)
	at org.pepsoft.worldpainter.NewWorldDialog.updatePreview(NewWorldDialog.java:599)
	at org.pepsoft.worldpainter.NewWorldDialog.fieldSeedFocusLost(NewWorldDialog.java:1423)

WorldPainter version: 2.5.1 (20180508164836)

java.version: 10.0.1
java.vendor: Oracle Corporation
java.vm.version: 10.0.1+10
java.vm.vendor: "Oracle Corporation"
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\vince
user.dir: C:\Program Files\WorldPainter
user.country: US
user.language: en

Free memory: 95034432 bytes
Total memory size: 161480704 bytes
Max memory size: 6354370560 bytes

Operation: null
Radius: 50
Brush: Plateau Circle (radius=50, brushShape=CIRCLE, level=0.51)/Constant Square (radius=0, brushShape=SQUARE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
Thanks for reporting this error! I'll fix it in the next release.

**Comment by xanderholstege** [comment]
wenn do u think the next relase is?
