### ISSUE TITLE
NPE on import

### ISSUE THREAD

**Issue by Captain-Chaos** [Captain-Chaos/WorldPainter#88]
`java.lang.NullPointerException: null
	at org.pepsoft.minecraft.MC113AnvilChunk.<init>(MC113AnvilChunk.java:59)
	at org.pepsoft.worldpainter.JavaPlatformProvider.createChunk(JavaPlatformProvider.java:46)
	at org.pepsoft.worldpainter.JavaPlatformProvider.createChunk(JavaPlatformProvider.java:35)
	at org.pepsoft.worldpainter.importing.JavaMapImporter.importDimension(JavaMapImporter.java:282)
	at org.pepsoft.worldpainter.importing.JavaMapImporter.doImport(JavaMapImporter.java:141)`

**Comment by Captain-Chaos** [comment]
See world1.zip.

**Comment by Captain-Chaos** [comment]
This was originally reported as an NPE on importing the specified world, using 2.5.8.2-SNAPSHOT. That was not reproducible; this map could be successfully imported using that version.

However, a more serious problem was discovered: this map has been damaged by Minecraft, and gets progressively further damaged while moving around in it in Minecraft 1.13.2! Swathes of chunks that already existed have been replaced by default or empty chunks, and while moving around in this map it gets progressively worse.

It seems likely that the cause is that this map was originally generated by WorldPainter, since it seems much less likely that Minecraft is prone to damaging existing maps this way.
