### ISSUE TITLE
NullPointerException on export/dimension properties

### ISSUE THREAD

**Issue by G1R-Productions** [Captain-Chaos/WorldPainter#90]
Latest Snapshot for 1.13

Experiencing a java nullpointerexception when I try to export a world as a minecraft map or look at the dimension properties menu. This occurs on all projects, new or pre-existing.

java.lang.NullPointerException: null
	at org.pepsoft.worldpainter.layers.exporters.ResourcesExporter$ResourcesExporterSettings.getChance(ResourcesExporter.java:209)
	at org.pepsoft.worldpainter.DimensionPropertiesEditor.loadSettings(DimensionPropertiesEditor.java:736)
	at org.pepsoft.worldpainter.DimensionPropertiesEditor.setDimension(DimensionPropertiesEditor.java:158)
	at org.pepsoft.worldpainter.DimensionPropertiesDialog.<init>(DimensionPropertiesDialog.java:32)
	at org.pepsoft.worldpainter.DimensionPropertiesDialog.<init>(DimensionPropertiesDialog.java:22)

WorldPainter version: 2.5.10.1-SNAPSHOT (20190222233555)

java.version: 1.8.0_202
java.vendor: Oracle Corporation
java.vm.version: 25.202-b08
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\Ghaz
user.dir: H:\Minecraft\Maps\WorldPainter [SNAPSHOT]
user.country: US
user.language: en

Free memory: 484330920 bytes
Total memory size: 771227648 bytes
Max memory size: 28559015936 bytes

World name: Generated World
Seed: 1839113055207579950
Bounds: -19, -19 => 19, 19
Height: 256
Number of tiles: 1521
Layers in use: 
Border: null @ 62
Sub surface material: Stone Mix
Water height: 62

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
I just released a new version of the snapshot in which this is fixed.
