### ISSUE TITLE
null error when exporting 

### ISSUE THREAD

**Issue by LukeCS1** [Captain-Chaos/WorldPainter#93]
java.lang.UnsupportedOperationException: null
	at org.pepsoft.minecraft.MC113AnvilChunk.getHighestNonAirBlock(MC113AnvilChunk.java:383)
	at org.pepsoft.worldpainter.exporting.LightingCalculator.calculatePrimaryLight(LightingCalculator.java:150)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lightingPass(AbstractWorldExporter.java:612)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.exportRegion(AbstractWorldExporter.java:748)
	at org.pepsoft.worldpainter.exporting.AbstractWorldExporter.lambda$parallelExportRegions$0(AbstractWorldExporter.java:274)

WorldPainter version: 2.5.10.1-SNAPSHOT (20190222233555)

java.version: 10.0.1
java.vendor: Oracle Corporation
java.vm.version: 10.0.1+10
java.vm.vendor: "Oracle Corporation"
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\lukec
user.dir: D:\Worldpainter\WorldPainter [SNAPSHOT]
user.country: GB
user.language: en

Free memory: 2343963368 bytes
Total memory size: 5897191424 bytes
Max memory size: 6402605056 bytes

World name: Euroasia Finish 2
Seed: -805098147246934562
Bounds: 0, 0 => 256, 127
Height: 256
Number of tiles: 32896
Layers in use: water, span trees, Swamp, yellow flower, white fliwers, red flwoers, Biome, Coal Ore, Quartz Block, purple flowers, Diamond Ore, brushh, brush, Lava, palms, Hardened Clay, Iron Ore, Gold Ore, Sakura trees, Clay Block, Frost, Birches, blue f,lowers, Clay Block, Sandstone, orange flowers
Border: WATER @ 1
Sub surface material: Stone
Water height: 1

Operation: null
Radius: 50
Brush: Plateau Circle (radius=0, brushShape=CIRCLE, level=1.0)/Sine Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.51/0.51
Zoom: 0
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment]
I just released a new version of the snapshot in which this is fixed!
