### ISSUE TITLE
No GUI on Red Hat fedora 29

### ISSUE THREAD

**Issue by Alex-DataSIM** [Captain-Chaos/WorldPainter#96]
I've tried the rpm, installer and tar.gz versions of worldpainter. All versions produce the same result.

Output:
```
[ahodges@localhost worldpainter-snapshot]$ ./worldpainter 
Could not load Logmanager "org.pepsoft.worldpainter.util.WPLogManager"
java.lang.ClassNotFoundException: org.pepsoft.worldpainter.util.WPLogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.logging.LogManager$1.run(LogManager.java:195)
	at java.util.logging.LogManager$1.run(LogManager.java:181)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at com.install4j.runtime.installer.helper.InstallerUtil.disablePreferencesLoggingImpl(InstallerUtil.java:586)
	at com.install4j.runtime.installer.helper.InstallerUtil.<clinit>(InstallerUtil.java:103)
	at com.install4j.runtime.launcher.FullLauncherHelper.getInstallerFile(FullLauncherHelper.java:86)
	at com.install4j.runtime.launcher.UnixLauncher.readProperties(UnixLauncher.java:108)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:43)
[2019-03-16 12:41:19,253] {INFO  } ( org.pepsoft.worldpainter.Main) Starting WorldPainter 2.5.11.1-SNAPSHOT (20190310202057)
[2019-03-16 12:41:19,255] {INFO  } ( org.pepsoft.worldpainter.Main) Running on Linux version 4.20.14-200.fc29.x86_64; architecture: amd64
[2019-03-16 12:41:19,256] {INFO  } ( org.pepsoft.worldpainter.Main) Running on Oracle Corporation Java version 1.8; maximum heap size: 3726 MB
[2019-03-16 12:41:19,257] {INFO  } ( org.pepsoft.worldpainter.Main) Hardware acceleration method: default
[2019-03-16 12:41:19,263] {INFO  } (o.p.worldpainter.Configuration) Configuration found in old location (/home/ahodges/.worldpainter); migrating it to new location (/home/ahodges/.worldpainter-snapshot)
[2019-03-16 12:41:19,295] {INFO  } (o.p.worldpainter.Configuration) Loading configuration from /home/ahodges/.worldpainter-snapshot/config
Matched minecraft:vine{east=false, south=false, north=false, west=false, up=false} to Vines(106):0
[2019-03-16 12:41:19,667] {INFO  } ( org.pepsoft.worldpainter.Main) Installation ID: 382b65e1-85a5-4ebe-953c-486a4ea5eaeb
[2019-03-16 12:41:19,694] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: DefaultLayerEditorProvider (version 2.5.11.1-SNAPSHOT)
[2019-03-16 12:41:19,694] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: Default (version 2.5.11.1-SNAPSHOT)
[2019-03-16 12:41:19,695] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: DefaultPlatforms (version 2.5.11.1-SNAPSHOT)
[2019-03-16 12:41:19,695] {INFO  } ( o.p.w.plugins.WPPluginManager) Loaded plugin: DefaultCustomObjects (version 2.5.11.1-SNAPSHOT)
[2019-03-16 12:41:19,699] {INFO  } ( org.pepsoft.worldpainter.Main) Available platform: Minecraft 1.13.2 or later (Anvil)
[2019-03-16 12:41:19,699] {INFO  } ( org.pepsoft.worldpainter.Main) Available platform: Minecraft 1.2 - 1.12 (Anvil)
[2019-03-16 12:41:19,699] {INFO  } ( org.pepsoft.worldpainter.Main) Available platform: Minecraft 1.1 (MCRegion)
[2019-03-16 12:41:19,700] {INFO  } (      o.p.w.PrivateContextImpl) Checking for updates
[2019-03-16 12:41:20,159] {INFO  } ( o.p.worldpainter.WorldFactory) Creating default world of 5 by 5 tiles (25 tiles total)
```

The program just hangs here consuming large amounts of cpu with no GUI.

**Comment by Captain-Chaos** [comment]
It seems to have something to do with Fedora's Java setup. It is incomplete or defective somehow. I was able to get it to work by installing the full OpenJDK with `dnf install java-1.8.0-openjdk-devel.x86_64`.

But even then it was behaving strangely. The brush was always filling its entire outline solid, rather than feathering at the edges or responding to the intensity slider. The tablet support was malfunctioning somehow. If this happens to you, you can disable that by adding the line `-Dorg.pepsoft.worldpainter.disableTabletSupport=true` to your `worldpainter.vmoptions` file according to [these](https://www.worldpainter.net/trac/wiki/AdvancedSettings) instructions, which fixed the issue for me.

Java on Fedora seems to be a bit of a mess. Let me know how you get on with the above.

**Comment by Alex-DataSIM** [comment]
This fix seemed to work. GUI opens normally now. Thanks @Captain-Chaos

**Comment by Captain-Chaos** [comment]
Glad to hear it! In that case I'll close the issue.
